# Explore here

In [ ]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/4GeeksAcademy/predicting-your-future-with-data/main/adult-census-income.csv')
df

In [ ]:
df.shape

In [ ]:
df = df.dropna()

In [ ]:
categoricas = ["workclass", "education", "marital.status", "occupation", 
            "relationship", "race", "sex", "native.country"]

In [ ]:
numeros = ["age", "fnlwgt", "education.num", "capital.gain", 
            "capital.loss", "hours.per.week"]

In [ ]:
df_cat = pd.get_dummies(df[cat_cols], drop_first=True)

In [ ]:
scaler = MinMaxScaler()
df_num = pd.DataFrame(scaler.fit_transform(df[num_cols]), columns=num_cols)

In [ ]:
df_processed = pd.concat([df_num, df_cat, df['income']], axis=1)

Simulamos perfil

In [ ]:
usuario = {
    'age': 30, 'fnlwgt': 200000, 'education.num': 9, 'capital.gain':0, 'capital.loss':0, 'hours.per.week':40,
    'workclass': 'Private', 'education': 'HS-grad', 'marital.status':'Never-married',
    'occupation': 'Other-service', 'relationship':'Not-in-family',
    'race':'White', 'sex':'Male', 'native.country': 'Mexico'
}

In [ ]:
usuario_num = pd.DataFrame([[
    usuario['age'],
    usuario['fnlwgt'],
    usuario['education.num'],
    usuario['capital.gain'],
    usuario['capital.loss'],
    usuario['hours.per.week'],
]], columns=num_cols)
usuario_num = pd.DataFrame(scaler.transform(usuario_num), columns=num_cols)

usuario_cat_dict = {}
for col in df_cat.columns:
    key_split = col.split('_', 1)
    fcol = key_split[0]
    fval = key_split[1]
    usuario_cat_dict[col] = int(str(usuario.get(fcol)) == fval)
usuario_cat = pd.DataFrame([usuario_cat_dict])

In [ ]:
usuario_vector = pd.concat([usuario_num, usuario_cat], axis=1)

Similitud con buenos perfiles

In [ ]:
perfiles_ricos = df_processed[df_processed['income']==1].drop('income', axis=1)

In [ ]:
print(df_processed['income'].value_counts())

In [42]:
perfiles_ricos = df_processed[df_processed['income'] == '>50K'].drop('income', axis=1)
perfiles_ricos

,age,fnlwgt,education.num,capital.gain,capital.loss,hours.per.week,workclass_Federal-gov,workclass_Local-gov,workclass_Never-worked,workclass_Private,...,native.country_Portugal,native.country_Puerto-Rico,native.country_Scotland,native.country_South,native.country_Taiwan,native.country_Thailand,native.country_Trinadad&Tobago,native.country_United-States,native.country_Vietnam,native.country_Yugoslavia
7,0.780822,0.051855,1.000000,0.0,0.845500,0.193878,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
9,0.328767,0.039223,0.600000,0.0,0.689624,0.602041,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
10,0.383562,0.108657,1.000000,0.0,0.689624,0.346939,False,False,False,True,...,False,False,False,False,False,False,False,True,False,False
11,0.287671,0.103395,0.933333,0.0,0.648301,0.448980,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
12,0.479452,0.079388,0.800000,0.0,0.648301,0.193878,False,False,False,True,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32539,0.232877,0.100468,0.800000,0.0,0.000000,0.551020,False,False,False,True,...,False,False,False,False,False,False,False,True,False,False
32541,0.739726,0.186826,1.000000,0.0,0.000000,0.091837,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
32547,0.301370,0.067382,0.733333,0.0,0.000000,0.193878,False,True,False,False,...,False,False,False,False,False,False,False,True,False,False
32555,0.493151,0.210253,0.866667,0.0,0.000000,0.397959,False,False,False,True,...,False,False,False,False,False,False,False,True,False,False
32558,0.315068,0.096500,0.533333,0.0,0.000000,0.397959,False,False,False,True,...,False,False,False,False,False,False,False,True,False,False

In [43]:
similitudes = cosine_similarity(usuario_vector, perfiles_ricos)[0]

In [44]:
top_n = 5
indices_recomendados = similitudes.argsort()[-top_n:][::-1]

In [45]:
recomendados = perfiles_ricos.iloc[indices_recomendados]
print("Perfiles recomendados para mejorar ingreso:")
print(recomendados)

Perfiles recomendados para mejorar ingreso:
            age    fnlwgt  education.num  capital.gain  capital.loss  \
15247  0.424658  0.173610       0.800000      0.000000           0.0
6207   0.191781  0.140737       0.533333      0.000000           0.0
31635  0.136986  0.091723       0.533333      0.000000           0.0
2261   0.164384  0.051358       0.533333      0.105201           0.0
15439  0.424658  0.127209       0.533333      0.000000           0.0

       hours.per.week  workclass_Federal-gov  workclass_Local-gov  \
15247        0.500000                  False                False
6207         0.397959                  False                False
31635        0.500000                  False                False
2261         0.397959                  False                False
15439        0.397959                  False                False

       workclass_Never-worked  workclass_Private  ...  \
15247                   False               True  ...
6207                    False               True  ...
31635                   False               True  ...
2261                    False               True  ...
15439                   False               True  ...

       native.country_Portugal  native.country_Puerto-Rico  \
15247                    False                       False
6207                     False                       False
31635                    False                       False
2261                     False                       False
15439                    False                       False

       native.country_Scotland  native.country_South  native.country_Taiwan  \
15247                    False                 False                  False
6207                     False                 False                  False
31635                    False                 False                  False
2261                     False                 False                  False
15439                    False                 False                  False

       native.country_Thailand  native.country_Trinadad&Tobago  \
15247                    False                           False
6207                     False                           False
31635                    False                           False
2261                     False                           False
15439                    False                           False

       native.country_United-States  native.country_Vietnam  \
15247                         False                   False
6207                          False                   False
31635                          True                   False
2261                           True                   False
15439                         False                   False

       native.country_Yugoslavia
15247                      False
6207                       False
31635                      False
2261                       False
15439                      False

[5 rows x 100 columns]

In [46]:
recomendados.shape

(5, 100)